title: The Jazz Cannons
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.5727181516122073
  lightness: 1
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  rhythmicContrast: 1
typography_spectrum: 0.8753495300188661
description: Step into the Swing
layout_spectrum: 0.9820151047315449
name: Jazz Cannons
